[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/local/bin/zld",
    "-C", "target-cpu=apple-m1",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "target-cpu=native"
]

#[profile.dev]
#debug = 1
#split-debuginfo = 'unpacked'

[profile.release]
#incremental = true
#debug = 1
lto = true
codegen-units = 1
strip = "debuginfo"
panic = "abort"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
#
#[profile.dev.package."*"]
#opt-level = 3